# https://docs.travis-ci.com/user/customizing-the-build/

sudo: false

language: node_js

node_js:
  - "6"

branches:
  only:
    - master

matrix:
  fast_finish: true

before_install:
  - npm install -g npm
  - npm --version

script: npm start ci
